### ISSUE TITLE
Integration in custom livewire components pages 

### ISSUE THREAD

**Issue by wagnerfnds** [wirechat/wirechat#5]
Hey Namu, hope youre fine!

Wirechat is awesome! 

Im trying to use Wirechat with FilamentPHP since both are TALL stack i guess it will work just fine.
I think there is something wrong (or im not knowing how to do it) about the guards when using filament. I keep getting redirected when trying to access /chats. 
Also would be nice to have the livewire component for the chat so we can import it on a filament page and keep it inside our Filament UI. What do you think? 

Also, im posting it here because i dont find any other place to do this post, so im sorry if it is the wrong place for this question. 

EIDT:

I make it work with auth know, but i have to make my filament app use the web guard, instead of the custom one i have created and informed on wirechat config (maybe a bug?) 

Now i want to put it inside a filament page :) 

Appreciate any help, thanks!!

**Comment by namumakwembo** [comment]
Hey, I appreciate your feedback about Wirechat and for bringing this to my attention!

I think the issue might be related to the auth() checks inside the components, which currently use the default guard. While I configured the guards to be respected in the routes, it seems I might have forgotten to also set up custom guards in the components. I haven’t tested Wirechat on a Filament app yet, but I’ll definitely look into this and address the issue as soon as possible.

Regarding adding a Livewire component for easy integration into Filament pages, that’s a great idea! I’m exploring how to embed the components so they can be used anywhere in the application.

Thanks again for the feedback , it really helps improve Wirechat! Feel free to share any other suggestions or issues you encounter. 😊

**Comment by namumakwembo** [comment]
After inspecting the issue and setting up an `admin` guard myself with FilamentPHP, I found that the redirection issue is related to the middleware configuration, rather than the components themselves .

To fix this, try to  update the Wirechat middleware in your published config file to use your custom guard (e.g., `auth:admin` for the admin guard).: like this

```php
'routes' => [
    ...
    'middleware' => ['web','auth:admin'],  // Use your custom guard here,
],
```

This should help resolve the issue, and you can replace `auth:admin` with whatever your custom guard is.

I’ll probably need to document this better in the future to make it clearer for other users. Let me know if this works for you or if you encounter any more issues, as there could be other factors at play!

**Comment by wagnerfnds** [comment]
Hey, the redirect stoped! Thank you! But it still not working the actions, like search a user to start a chat, maybe something wrong because it is side by side with filament? in a clean installation with breeze it work like a charm

**Comment by namumakwembo** [comment]
Glad to hear the redirection issue is resolved!

Can you please elaborate on how you’re trying to use the package? Are you accessing the `/chats ` route as a Filament admin, or are you integrating it differently within your Filament setup?

For reference, I was able to access, search, and create chats while logged in as a Filament user/admin using a custom guard. Let me know more about your specific use case, and I’ll do my best to assist further!

**Comment by wagnerfnds** [comment]
Is there any config i should do when im not using the default user model? maybe define which field is the id? im getting this when im trying to create a group via /chats 

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'participantable_id' cannot be null

 i can even see the other users names, but the click didnt work and it dont filter by name. i think is because it is not the default user model. 

I managed to put the UI inside a filament page using the <livewire:chats/>  but then the clicks didnt work to select users etc

https://github.com/user-attachments/assets/40616b67-2bbc-4b9d-8a25-553572ceba41

**Comment by namumakwembo** [comment]
Hello, 

No configuration is needed when using a different model, such as `Admin`. Wirechat is designed to work smoothly with any authenticatable model. However, after reviewing your video, it seems the issue originates from the search functionality and how the results are returned. Specifically, it appears that the `id` field is missing from the search results. As a result, when attempting to create a private chat, no matching model is found, which leads to no response being sent (I should probably add an error message to handle this scenario more gracefully).

Additionally, the integrity error (`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'participantable_id' cannot be null`) occurs because the missing `id` causes the participantable ID to be null. 

Did you customize the `searchChatables()` method provided by the `Chatable` trait? If not, I recommend reviewing or configuring it to ensure the correct results are returned. Here's an example for searching through the `User` model (the default):

```php
/**
 * Search for users when creating a new chat or adding members to a group.
 * Customize the search logic to limit results, such as restricting to friends or eligible users only.
 */
public function searchChatables(string $query): ?Collection
{
    $searchableFields = ['name'];
    return User::where(function ($queryBuilder) use ($searchableFields, $query) {
        foreach ($searchableFields as $field) {
            $queryBuilder->orWhere($field, 'LIKE', '%'.$query.'%');
        }
    })
    ->limit(20)
    ->get();
}
```
Please Let me know ,  if the issue still persists

**Comment by wagnerfnds** [comment]
Im pretty sure the problem is with my project. But i appreciate your help. If i manage to make it work i come back here to update you and maybe bring some insights, again, very thank you for your time, and your project is awesome!

**Comment by namumakwembo** [comment]
Hey, no worries! I’m glad I could help a bit. If you figure it out, definitely swing back and share—would be awesome to hear what worked

**Comment by christoferw** [comment]
@wagnerfnds @namumakwembo we want to integrate it into an existing filament project - can you share your experience with it? it's not working out of the box yet in our case, but maybe we support for a general solution.

**Comment by wagnerfnds** [comment]
@christoferw i kinda published the views and migrate it to a filament page. but keep in mind if you do this you will have to keep tracking when they update the views to replicate it again
